spring:
  h2:
    console:
      enabled: true
      path: /h2
  liquibase:
    change-log: classpath:/db.changelog-master.xml
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver